export const dracthyrNameOneM = {
    : "Abereth",
    : "Algeth'ar",
    : "Alsiaszar",
    : "Arrosh",
    : "Azurathel",
    : "Bernaisez",
    : "Burigos",
    : "Chrovo",
    : "Chrozon",
    : "Coulisa",
    : "Cuzolth",
    : "Dialash",
    : "Dathendrash",
    : "Damos",
    : "Elarthresh",
    : "Emberath",
    : "Emishalan",
    : "Fusethrian",
    : "Geradran",
    : "Haerothal",
    : "Haiku",
    : "Herac",
    : "Hermin",
    : "Imareth",
    : "Iristella",
    : "Iristimat",
    : "Iyazael",
    : "Kajithalan",
    : "Kazure",
    : "Kerzanthi",
    : "Keskahz",
    : "Kethahn",
    : "Kodethi",
    : "Kokoslah",
    : "Korvelnor",
    : "Krenzen",
    : "Krozhalan",
    : "Krozuthar",
    : "Kykrolian",
    : "Mercatethel",
    : "Malifron",
}

export const dracthyrNameOneF = {
    : "Alanatheth",
    : "Algeth'ar",
    : "Alzinathel",
    : "Andoris",
    : "Brendormi",
    : "Cindrethresh",
    : "Dervishian",
    : "Destia",
    : "Ekrati",
    : "Emberthal",
    : "Eraleshk",
    : "Erza",
    : "Foxigleth",
    : "Glamora",
    : "Hippeusti",
    : "Jyhanna",
    : "Katrinasa",
    : "Kemora",
    : "Ketholia",
    : "Kotheshal",
    : "Kurazidaia",
    : "Kozastran",
    : "Magera",
    : "Makko",
    : "Malicia",
    : "Melonee",
    : "Melonia",
    : "Mezeri",
    : "Mythressa",
}

export const dracthyrNameTwo = {
    : "Freshscale",
    : "",
    : "Baneflare",
}