export const dracthyrNameOneM = {
    : "Abereth",
    : "Algeth'ar",
    : "Alsiaszar",
    : "Arrosh",
    : "Azurathel",
    : "Bernaisez",
    : "Burigos",
    : "Chrovo",
    : "Chrozon",
    : "Coulisa",
    : "Cuzolth",
    : "Dialash",
    : "Dathendrash",
    : "Damos",
    : "Elarthresh",
    : "Emberath",
    : "Emishalan",
    : "Fusethrian",
    : "Geradran",
    : "Haerothal",
    : "Haiku",
    : "Herac",
    : "Hermin",
    : "Imareth",
    : "Iristella",
    : "Iristimat",
    : "Iyazael",
}

export const dracthyrNameOneF = {
    : "Alanatheth",
    : "Algeth'ar",
    : "Alzinathel",
    : "Andoris",
    : "Brendormi",
    : "Cindrethresh",
    : "Dervishian",
    : "Destia",
    : "Ekrati",
    : "Emberthal",
    : "Eraleshk",
    : "Erza",
    : "Foxigleth",
    : "Glamora",
    : "Hippeusti",
}

export const dracthyrNameTwo = {
    : "Freshscale",
    : "",
    : "Baneflare",
}