export const highmountainTaurenNameOneM = {
    : "Ates",
    : "Azgo",
    : "Biehn",
    : "Banoth",
    : "Degar",
    : "Jafel",
    : "Torok",
    : "Tugar",
    : "Caruk",
    : "Oraine",
    : "Galica",
    : "Micah",
    : "Kalo",
    : "Patri",
    : "Hanye",
    : "Halia",
    : "Jaffe",
    : "Hosan",
    : "Hern",
    : "Creel",
}

export const highmountainTaurenNameOneF = {
    : "Halla",
    : "Chulani",
    : "Mora",
    : "Bilge",
    : "Tallelah",
    : "Kurd",
    : "Wyna",
    : "A'te",
}

export const highmountainTaurenNameTwo = {
    : "Amberfur",
    : "Bloodshield",
    : "Bloodtotem",
    : "Bloodwind",
    : "Blurblades",
    : "Bonehoof",
    : "Bravepaw",
    : "Breezehorn",
    : "Broadhoof",
    : "Broadhorn",
    : "Brownmane",
    : "Burkhorn",
    : "Burnedhoof",
    : "Butterhoof",
    : "Chargefeather",
    : "Rivenhoof",
    : "Clearpath",
    : "Clearwater",
    : "Cliffhoof",
    : "Cloudbreath",
    : "Cloudeye",
    : "Cloudfeather",
    : "Cloudhoof",
    : "Cloudwalker",
    : "Cragfeather",
}