export const orcNameOneM = {
    : "Thragg",
    : "Grulm",
    : "Gorrok",
    : "Hrakk",
    : "Durgg",
    : "Krag",
    : "Rokk",
    : "Ulgar",
    : "Burgol",
    : "Zog",
    : "Mogar",
    : "Gorak",
    : "Grishnak",
    : "Brakka",
    : "Narg",
    : "Snagrot",
    : "Moggrim",
    : "Skarnak",
    : "Durgash",
    : "Thrakka",
    : "Lokthra",
    : "Drokthul",
    : "Azgul",
    : "Gulmok",
    : "Zargul",
    : "Rokar",
    : "Brugor",
    : "Zulgrak",
    : "Gruul",
    : "Thrashgore",
    : "Gorchop'",
    : "Gromnar",
    : "Drovast",
    : "Vargul",
    : "Moktan",
    : "Zuggthar",
    : "Uruk",
    : "Throk",
    : "Gnash",
    : "Nartoe",
    : "Zhor",
    : "Gunchin",
    : "Mobrukk",
    : "Brar",
    : "Ratnob",
    : "Bashuk",
    : "Zugug",
    : "Brokil",
    : "Pargu",
    : "Skargob",
    : "Orknack",
    : "Noogugh",
    : "Kurdan",
    : "Homraz",
    : "Sharn",
    : "Morgut",
    : "Snagagor",
    : "Matuk",
    : "Gael",
    : "Usunaar",
    : "Agis",
    : "Sundryl",
    : "Mugdul",
    : "",
}

export const orcNameOneF = {
    : "",
    : "",
}

export const orcNameTwo = {
    : "Bloodfang",
    : "Blackskull",
    : "Ironhide",
    : "Gorehammer",
    : "Darkblade",
    : "Skullcrusher",
    : "Doombringer",
    : "Deathgrasp",
    : "Warbane",
    : "Ragefire",
    : "Bonebreaker",
    : "Grimtusk",
    : "Shadowrend",
    : "Steelbender",
    : "Thunderfist",
    : "Nightshade",
    : "Ashbringer",
    : "Bonechewer",
    : "Ironfist",
    : "Bloodspike",
    : "Skullsplitter",
    : "Grimjaw",
    : "Ironfang",
    : "Doomaxe",
    : "The Reaper",
    : "Vileheart",
    : "Felblood",
    : "Steelgore",
    : "Darkthorn",
    : "Razorthorn",
    : "Hellscream",
    : "Goreband",
    : "Ashenclaw",
    : "Blazefury",
    : "Warscar",
    : "Blackthorn",
    : "Bloodrender",
    : "Warsoul",
    : "Grimweaver",
    : "Grimshadow",
    : "Blackmaw",
    : "Deathgrip",
    : "Boneshatter",
    : "Darkblade",
    : "Grimtalon",
    : "Felheart",
    : "Darkrage",
    : "Hellfire",
    : "Razortusk",
    : "Brokentusk",
    : "Barehand",
    : "The Great",
    : "The Vicious",
    : "The Giant",
    : "The Angry",
    : "Wolfslayer",
    : "Firebog",
    : "The Wretched",
    : "The Grim",
    : "Grimwall",
    : "The Reckless",
    : "Deathbringer",
    : "Giantblood",
    : "",
}