export const pandarenNameOneM = {
    : "Liu",
    : "Li",
    : "Lin",
    : "Hann",
    : "Hight",
    : "Peizhi",
    : "Liana",
    : "Shaohao",
    : "Shang",
    : "Airan",
    : "Hong",
    : "Mushi",
    : "Gingo",
    : "Alin",
    : "An",
    : "Ang",
    : "Andi",
    : "Apo",
    : "Yun",
    : "Teng",
    : "Chiahui",
    : "Kun",
    : "Din",
    : "Azzo",
}

export const pandarenNameOneF = {
    : "Blanche",
    : "Anji",
    : "Aster",
    : "Ginsa",
    : "Kata",
    : "Arie",
    : "Lin",
    : "Ju",
    : "Jiayi",
    : "Cui",
    : "Anna",
    : "Anli",
    : "Chiu",
    : "Lin",
    : "Ling",
    : "Abra",
    : "Adele",
    : "Adelee",
    : "Aerial",
    : "Ahna",
    : "Ahone",
    : "Ai",
    : "Aichi",
    : "Aiko",
    : "Aki",
    : "Hara",
    : "Almai",
    : "Amai",
    : "Amalia",
    : "Ami",
}

export const pandarenNameTwo = {
    : "Bramblestaff",
    : "Brightcask",
    : "Chao",
    : "Wei",
    : "Fei",
    : "Dagu",
    : "Goldendraft",
    : "Heartfist",
    : "Mossbeard",
    : "Qi",
    : "Stormstout",
    : "Windfur",
    : "Xi",
    : "Airsquat",
    : "Alehearth",
    : "Alebelly",
    : "Alebottom",
    : "Applebarrel",
    : "Applebloom",
    : "Arroweye",
    : "Ashpaw",
    : "Autumnleaf",
    : "Autumnlight",
    : "Ayala",
    : "Arina",
}