export const trollNameOneM = {
    : "Akil'zon",
    : "Atai'natha",
    : "Daakara",
    : "Gan'dranda",
    : "Shadrak",
    : "Zul'arek",
    : "Gree",
    : "Jan'alai",
    : "Halazzi",
    : "Jin'zakk",
    : "Hameya",
    : "Kazra'jin",
    : "Hulg",
    : "Kel'gash",
    : "Jintha",
    : "Krag'jin",
    : "Kama",
    : "Krul'tan",
    : "Katoom",
    : "Mai'jin",
    : "Kul'krazahn",
    : "Kotonga",
    : "Moz'jin",
    : "Mith'rethis",
    : "Malacrass",
    : "Ongo'longo",
    : "Malkhor",
    : "Ral'jin",
    : "Otho",
    : "Renn'az",
    : "Nalorakk",
    : "Rin'ji",
    : "Nimar",
    : "Thresh'jin",
    : "Otembe",
    : "Panogo",
    : "Qeeju",
    : "Retherokk",
    : "Ter'lij",
    : "Shnel",
    : "Vex'tul",
    : "Timan",
    : "Zul'Brin",
    : "Tregla",
    : "Zul'jin",
    : "Marli",
    : "Zul'Marosh",
    : "Umboda",
    : "Zul'rogg",
    : "Voone",
    : "Vorsh",
    : "Zalas",
    : "Zaeldarr",
}

export const trollNameOneF = {
    : "Hexx",
    : "Qiaga",
    : "Yayo'jin",
    : "Vosh'gajin",
    : "Ojin'ba",
    : "Morta'gya",
    : "Hitah'ya",
}

export const trollNameTwo = {
    : "Eaglebane",
    : "Moji'ko",
    : "Hatefowler",
    : "Torntusk",
    : "Twotoes",
    : "Threeheads",
    : "Witherbark",
    : "Warpbranch",
    : "Witherheart",
}