export const voidElfNameOneM = {
    : "Aevedos",
    : "Atynar",
    : "Celosel",
    : "Matthias",
    : "Dewil",
    : "Nethandril",
    : "Kelain",
    : "Kholv",
    : "Lorinas",
    : "Umbric",
    : "Mendaci",
    : "Grady",
}

export const voidElfNameOneF = {
    : "Savia",
    : "Aowyn",
    : "Crysta",
    : "Crystalynn",
    : "Danessa",
    : "Leana",
    : "Elestrae",
    : "Selina",
    : "Esmer",
    : "Faedra",
    : "Jaelora",
    : "Kavia",
    : "Lockeye",
    : "Haalie",
    : "Falania",
    : "Keira",
}

export const voidElfNameTwo = {
    : "Anguossa",
    : "Nightgiver",
    : "Darkwall",
    : "Darkwind",
    : "Dawnshard",
    : "Duskraven",
    : "Duskthorn",
    : "Duskwalker",
    : "Evenshade",
    : "Millionia",
    : "Nightsoul",
    : "Onyxraven",
    : "Prett",
}