export const vulperaNameOneM = {
    : "Noko",
    : "Amre",
    : "Dust",
    : "Boots",
    : "Heiro",
    : "Hakasi",
    : "Hagashi",
    : "Jenoh",
    : "Keerin",
    : "Keeyo",
    : "Kenzou",
    : "Keshet",
    : "Kipp",
    : "Kiro",
    : "Kitt",
    : "Lugo",
    : "Meeki",
    : "Mekaru",
    : "Mikrin",
    : "Mnyeh",
    : "Narishi",
    : "Rabul",
    : "Rai",
    : "Raka",
    : "Renka",
    : "Rikati",
    : "Rudo",
    : "Romu",
    : "Scrumpy",
    : "Sheko",
    : "Shuko",
}

export const vulperaNameOneF = {
    : "Aisha",
    : "Selene",
    : "Rori",
    : "Rinka",
    : "Ranah",
    : "Ahna",
    : "Eudora",
    : "Eliani",
    : "Evie",
    : "Boots",
    : "Fari",
    : "Fifi",
    : "Elly",
    : "Gitah",
    : "Haniko",
    : "Hilda",
    : "Jahri",
    : "Jaki",
    : "Jena",
    : "Jeni",
    : "Kona",
    : "Korky",
    : "Kusa",
    : "Iyali",
    : "Leda",
    : "Maaz",
    : "Maiya",
    : "Meerah",
    : "Miri",
    : "Neri",
    : "Nilsa",
    : "Nisha",
    : "Norah",
    : "Olive",
    : "Omi",
    : "Piku",
}

export const vulperaNameTwo = {
    : "Fraze",
    : "Dibblefur",
}