export const worgenNameOneM = {
    : "Looper",
    : "Anatoly",
    : "Jacob",
    : "Kadus",
    : "Falcon",
    : "Josiah",
    : "Joe",
    : "Michael",
    : "Isaac",
    : "Lefteye",
    : "Berard",
    : "Wolfgrimm",
    : "Ivar",
    : "Renthal",
    : "Bodrin",
    : "Brent",
    : "Briggs",
    : "Barton",
    : "Brixton",
    : "Brock",
    : "Burke",
    : "Gabriel",
    : "Bruce",
}

export const worgenNameOneF = {
    : "Abigail",
    : "Adella",
    : "Mina",
    : "Jeanine",
    : "Theresa",
    : "Lorena",
    : "Lefteye",
    : "Hemma",
    : "Bernice",
    : "Jane",
    : "Rachelle",
    : "Celestra",
    : "Tatia",
    : "Larissa",
}

export const worgenNameTwo = {
    : "Aldan",
    : "Allen",
    : "Amrell",
    : "Anders",
    : "Arkadian",
    : "Atherton",
    : "Avery",
    : "Barker",
    : "Barkskin",
    : "Bartwell",
    : "Bedernik",
    : "Belle",
    : "Bentham",
    : "Beringer",
    : "Black",
    : "Blackhowl",
    : "Blackmange",
    : "Blackmantle",
    : "Blackmaw",
    : "Bloodfang",
    : "Bloodhowl",
    : "Brigham",
    : "Brightmoon",
    : "Brine",
    : "Burns",
    : "Bussell",
    : "Bybee",
}