export const zandalariTrollNameOneM = {
    : "Garajal",
    : "Geedae",
    : "Jahn",
    : "Manzul",
    : "Zakrajan",
    : "Ouda",
    : "Ujunta",
    : "Valjabu",
    : "Venoxis",
    : "Vilnakdor",
    : "Wanbe",
    : "Wunto",
    : "Zanza",
    : "Kanzim",
    : "Zulsan",
    : "A'akul",
    : "A'danu",
    : "A'dru",
    : "Jamil",
    : "Aht'lutal",
    : "Ahlswede",
    : "Al'tabim",
    : "Al'chukla",
    : "Akk'al",
    : "Akil'amon",
    : "Ahunae",
    : "Aitan",
    : "Alex",
    : "Aljabri",
    : "Amon",
    : "Anji",
    : "Ansari",
    : "Arbo",
    : "Aronson",
    : "Aycee",
    : "Azi",
    : "Azibo",
}

export const zandalariTrollNameOneF = {
    : "Dafini",
    : "Azala",
    : "Atulanji",
    : "Ash'tari",
    : "Asgari",
    : "Arlokk",
    : "Apari",
    : "Anaasha",
    : "Shinga",
    : "Duba",
    : "Grenja",
    : "Keula",
    : "Malaja",
    : "Ruka",
    : "Salazae",
    : "Tizeja",
    : "Volni",
    : "Zamcha",
    : "Karaja",
    : "Tastoa",
    : "Alun'za",
    : "Aka'ali",
    : "Atal'Jani",
    : "Akunda",
    : "Aman",
}

export const zandalariTrollNameTwo = {
    : "Deathwalker",
    : "Zubo",
    : "Abul'housin",
    : "Ack'uff",
}